### ISSUE TITLE
Select удаление значения и ссылка

### ISSUE THREAD

**Issue by cheburatino** [pepelazz/nla-framework#2]
Добавить возможность удалять значение и ссылку в виде аватарки

**Comment by pepelazz** [comment]
добавил параметры **isShowLink** и  **isClearable**

`t.GetFldRef("industry_id", "отрасль", "industry", [][]int{{5, 1}}, "col-4", "isShowLink", "isClearable")`

![image](https://user-images.githubusercontent.com/3218281/83035898-ada85f80-a042-11ea-9944-e0cebce0949c.png)
